/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.ejercicio4;

/**
 *
 * @author PC114
 */
public class InicioJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InicioJPanel
     */
    public InicioJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonMaximo_rendimiento = new javax.swing.JRadioButton();
        jRadioButtonEquilibrado = new javax.swing.JRadioButton();
        jRadioButtonAhorro_bateria = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelEstado_bateria = new javax.swing.JLabel();
        jProgressBarBateria = new javax.swing.JProgressBar();
        jLabelBluethooth = new javax.swing.JLabel();
        jComboBoxBluethooth = new javax.swing.JComboBox<>();

        setLayout(new java.awt.GridLayout(1, 2));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(5, 0));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLabel1.setText("Inicio");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 1, 1));
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel2.setText("Modos de energia:");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 1, 1));
        jPanel1.add(jLabel2);

        buttonGroup1.add(jRadioButtonMaximo_rendimiento);
        jRadioButtonMaximo_rendimiento.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jRadioButtonMaximo_rendimiento.setText("Maximo rendimiento");
        jRadioButtonMaximo_rendimiento.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 1, 1));
        jPanel1.add(jRadioButtonMaximo_rendimiento);

        buttonGroup1.add(jRadioButtonEquilibrado);
        jRadioButtonEquilibrado.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jRadioButtonEquilibrado.setText("Equilibrado");
        jRadioButtonEquilibrado.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 1, 1));
        jPanel1.add(jRadioButtonEquilibrado);

        buttonGroup1.add(jRadioButtonAhorro_bateria);
        jRadioButtonAhorro_bateria.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jRadioButtonAhorro_bateria.setText("Ahorro de bateria");
        jRadioButtonAhorro_bateria.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 1, 1));
        jPanel1.add(jRadioButtonAhorro_bateria);

        add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(4, 0));

        jLabelEstado_bateria.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelEstado_bateria.setText("Estado de la bateria:");
        jLabelEstado_bateria.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabelEstado_bateria.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 40, 1, 1));
        jPanel2.add(jLabelEstado_bateria);

        jProgressBarBateria.setBackground(java.awt.Color.green);
        jProgressBarBateria.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 30, 60, 30));
        jPanel2.add(jProgressBarBateria);

        jLabelBluethooth.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBluethooth.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelBluethooth.setText("Dispositivos Bluethooth:");
        jLabelBluethooth.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel2.add(jLabelBluethooth);

        jComboBoxBluethooth.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jComboBoxBluethooth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cascos_AP9", "Smart_tv_samsung", "DualSense_Wireless_Controller" }));
        jComboBoxBluethooth.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        jPanel2.add(jComboBoxBluethooth);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBoxBluethooth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBluethooth;
    private javax.swing.JLabel jLabelEstado_bateria;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBarBateria;
    private javax.swing.JRadioButton jRadioButtonAhorro_bateria;
    private javax.swing.JRadioButton jRadioButtonEquilibrado;
    private javax.swing.JRadioButton jRadioButtonMaximo_rendimiento;
    // End of variables declaration//GEN-END:variables
}
