/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejercicio4;

import java.awt.CardLayout;

/**
 *
 * @author PC114
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private CardLayout cardLayout;
    public VentanaPrincipal() {
        initComponents();
    }
    
    private void configurarCardLayout(){
        cardLayout = (CardLayout) jPanel2.getLayout();
        
        jPanel2.add(new InicioJPanel(),"Inicio");
        jPanel2.add(new JPanelCuentas(),"Cuentas");
        jPanel2.add(new JPanelIdioma(),"Idioma");
        jPanel2.add(new JPanelSistema(),"Sistema");
        jPanel2.add(new JPanelUpdate(),"Update");
        
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jButtonInicio = new javax.swing.JButton();
        jButtonSistema = new javax.swing.JButton();
        jButtonCuentas = new javax.swing.JButton();
        jButtonIdioma = new javax.swing.JButton();
        jButtonWindows_Update = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(232, 232, 252));
        jPanel1.setLayout(new java.awt.GridLayout(9, 0));

        jButtonInicio.setBackground(new java.awt.Color(232, 232, 252));
        jButtonInicio.setText("Inicio");
        jButtonInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonInicio);

        jButtonSistema.setBackground(new java.awt.Color(232, 232, 252));
        jButtonSistema.setText("Sistema");
        jButtonSistema.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSistemaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSistema);

        jButtonCuentas.setBackground(new java.awt.Color(232, 232, 252));
        jButtonCuentas.setText("Cuentas de usuario");
        jButtonCuentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuentasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCuentas);

        jButtonIdioma.setBackground(new java.awt.Color(232, 232, 252));
        jButtonIdioma.setText("Idioma");
        jButtonIdioma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIdiomaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonIdioma);

        jButtonWindows_Update.setBackground(new java.awt.Color(232, 232, 252));
        jButtonWindows_Update.setText("Windows Update");
        jButtonWindows_Update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonWindows_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWindows_UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonWindows_Update);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioActionPerformed
        cardLayout.show(jPanel2, "Inicio");
    }//GEN-LAST:event_jButtonInicioActionPerformed

    private void jButtonSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSistemaActionPerformed
        cardLayout.show(jPanel2, "Sistema");
    }//GEN-LAST:event_jButtonSistemaActionPerformed

    private void jButtonCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuentasActionPerformed
        cardLayout.show(jPanel2, "Cuentas");
    }//GEN-LAST:event_jButtonCuentasActionPerformed

    private void jButtonIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIdiomaActionPerformed
        cardLayout.show(jPanel2, "Idioma");
    }//GEN-LAST:event_jButtonIdiomaActionPerformed

    private void jButtonWindows_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWindows_UpdateActionPerformed
        cardLayout.show(jPanel2, "Update");
    }//GEN-LAST:event_jButtonWindows_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCuentas;
    private javax.swing.JButton jButtonIdioma;
    private javax.swing.JButton jButtonInicio;
    private javax.swing.JButton jButtonSistema;
    private javax.swing.JButton jButtonWindows_Update;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
